// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupZiboInstallation(arg1) {
  return window['go']['main']['App']['BackupZiboInstallation'](arg1);
}

export function CheckXPlanePath(arg1) {
  return window['go']['main']['App']['CheckXPlanePath'](arg1);
}

export function DownloadZibo(arg1) {
  return window['go']['main']['App']['DownloadZibo'](arg1);
}

export function FindZiboInstallationDetails() {
  return window['go']['main']['App']['FindZiboInstallationDetails']();
}

export function GetAvailableLiveries() {
  return window['go']['main']['App']['GetAvailableLiveries']();
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetCachedFiles() {
  return window['go']['main']['App']['GetCachedFiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadDetails(arg1) {
  return window['go']['main']['App']['GetDownloadDetails'](arg1);
}

export function GetLiveries(arg1) {
  return window['go']['main']['App']['GetLiveries'](arg1);
}

export function InstallZibo(arg1, arg2) {
  return window['go']['main']['App']['InstallZibo'](arg1, arg2);
}

export function IsXPlanePathConfigured() {
  return window['go']['main']['App']['IsXPlanePathConfigured']();
}

export function OpenDirDialog() {
  return window['go']['main']['App']['OpenDirDialog']();
}

export function RestoreZiboInstallation(arg1, arg2) {
  return window['go']['main']['App']['RestoreZiboInstallation'](arg1, arg2);
}

export function UpdateZibo(arg1, arg2) {
  return window['go']['main']['App']['UpdateZibo'](arg1, arg2);
}
