// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function BackupZiboInstallation(arg1:utils.ZiboInstallation):Promise<boolean>;

export function CheckXPlanePath(arg1:string):Promise<boolean>;

export function DownloadZibo(arg1:boolean):Promise<boolean>;

export function FindZiboInstallationDetails():Promise<utils.ZiboInstallation>;

export function GetConfig():Promise<utils.Config>;

export function GetDownloadDetails(arg1:boolean):Promise<number>;

export function InstallZibo(arg1:utils.ZiboInstallation):Promise<void>;

export function IsXPlanePathConfigured():Promise<boolean>;

export function OpenDirDialog():Promise<string>;

export function RestoreZiboInstallation(arg1:utils.ZiboInstallation):Promise<boolean>;

export function UpdateZibo(arg1:utils.ZiboInstallation):Promise<void>;
